index_name_notreat = "baseline"
index_name_withtreat = "baseline_pre_process"
index_name_notreatdfr = "baseline_dfr"
index_name_withtreatdfr = "baseline_pre_process_dfr"
index_name_notreattfidf = "baseline_tfidf"
index_name_withtreattfidf = "baseline_pre_process_tfidf"
